cyoa-step1:Story.hpp Page.hpp cyoa-step1.cpp
	g++ -pedantic -g --std=gnu++98 -Werror -Wall -o cyoa-step1 cyoa-step1.cpp
cyoa-step2:Story.hpp Page.hpp cyoa-step2.cpp
	g++ -pedantic -g --std=gnu++98 -Werror -Wall -o cyoa-step2 cyoa-step2.cpp
